import os
import zipfile
from datetime import datetime
from pathlib import Path
import fnmatch
import re

# ============ 可调参数 ============

MAX_FILE_SIZE_MB = 25
OUTPUT_TO_DESKTOP = True

# ✅ 关键：只收“源码/配置”文件（强烈推荐）
SOURCE_ONLY = True

# ✅ 是否从 .env 自动生成 .env.example（仅保留 key，不保留值）
GENERATE_ENV_EXAMPLE = True
# 如果 .env.example 已存在，是否仍强制覆盖重建
FORCE_REGEN_ENV_EXAMPLE = True
# 优先从这些文件生成（找到第一个存在的就用）
ENV_CANDIDATES = [".env", ".env.local", ".env.production", ".env.development"]

# 只要路径里包含这些目录名（任意层级），就跳过（常见数据/产物）
EXCLUDE_DIRS = {
    "node_modules", ".next", ".git", ".turbo", ".cache", ".vscode", ".idea",
    "__pycache__", "dist", "build", "coverage", ".output", ".vercel",
    "tmp", "temp", "logs",
    ".pnpm-store",
}

# 额外：按“目录名模式”排除（常见 volume/data 目录）
EXCLUDE_DIRNAME_GLOBS = [
    "*data*", "*volume*", "*volumes*",  "*cache*",
    "*loki*", "*grafana*", "*promtail*",
]

# 永久排除的文件名模式（敏感 / 二进制 / 巨大）
EXCLUDE_FILE_GLOBS = [
    # secrets（注意：.env.example 通过 should_exclude 的例外逻辑保留）
    ".env", ".env.*",
    "*.pem", "*.key", "*.p12", "*.pfx", "*.crt", "*.cer", "*.der",
    "*id_rsa*", "*id_ed25519*",

    # db / logs
    "*.sqlite", "*.sqlite3", "*.db", "*.log",

    # archives
    "*.zip", "*.tar", "*.tgz", "*.gz", "*.7z", "*.rar",

    # media/fonts (通常体积大)
    "*.png", "*.jpg", "*.jpeg", "*.webp", "*.gif", "*.bmp", "*.ico",
    "*.mp4", "*.mov", "*.avi", "*.mkv",
    "*.mp3", "*.wav", "*.flac",
    "*.pdf",
    "*.ttf", "*.otf", "*.woff", "*.woff2",
]

# ✅ SOURCE_ONLY=True 时，会用这个“允许后缀白名单”
# （monorepo + 小程序骨架：补充 .wxml/.wxss/.wxs）
ALLOW_EXTS = {
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".json", ".md", ".txt",
    ".yml", ".yaml",
    ".prisma", ".sql",
    ".sh", ".bash", ".zsh", ".ps1", ".py",
    ".toml", ".ini", ".properties",
    ".css", ".scss",
    ".html",
    # WeChat Mini Program
    ".wxml", ".wxss", ".wxs",
}

# 根目录额外强制包含（即使没后缀）
FORCE_INCLUDE_FILENAMES = {
    # docker
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "docker-compose.prod.yml",

    # monorepo / pkg managers
    "package.json",
    "pnpm-lock.yaml",
    "pnpm-workspace.yaml",
    "pnpm-workspace.yml",
    "package-lock.json",
    "yarn.lock",

    # next / tooling
    "next.config.js",
    "next.config.mjs",
    "next.config.ts",
    "tsconfig.json",
    "postcss.config.js",
    "tailwind.config.js",

    # docs
    "MODULES.md",
    "OPERATIONS.md",
    "PROMPTING.md",
    "SECURITY.md",
    "README.md",
    "LICENSE",

    # optional dotfiles
    ".npmrc",
    ".nvmrc",
    ".node-version",
    ".editorconfig",
    ".gitignore",
    ".gitattributes",
    ".dockerignore",
}

TOP_LARGEST_PRINT = 30  # 打印最大的 N 个文件用于定位

# ============ 工具函数 ============

def get_desktop_dir() -> Path:
    home = Path.home()
    desktop = home / "Desktop"
    return desktop if desktop.exists() else home

def match_any_glob(name: str, globs) -> bool:
    for g in globs:
        if fnmatch.fnmatch(name, g):
            return True
    return False

def sanitize_env_line(line: str) -> str:
    """
    将 .env 的一行转换为 .env.example 的安全格式：保留 key，不保留 value。
    规则：
    - 注释/空行原样保留
    - export KEY=VALUE -> KEY=
    - KEY=VALUE -> KEY=
    - KEY:VALUE 这类不常见格式不处理（原样保留）
    """
    raw = line.rstrip("\n")
    stripped = raw.strip()

    if stripped == "" or stripped.startswith("#"):
        return raw

    # keep inline comments but strip values
    # handle "export KEY=VALUE"
    m = re.match(r"^\s*export\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$", raw)
    if m:
        key = m.group(1)
        return f"{key}="

    # handle "KEY=VALUE"
    m = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$", raw)
    if m:
        key = m.group(1)
        return f"{key}="

    return raw

def ensure_env_example(base_dir: Path) -> None:
    if not GENERATE_ENV_EXAMPLE:
        return

    target = base_dir / ".env.example"
    if target.exists() and not FORCE_REGEN_ENV_EXAMPLE:
        return

    src = None
    for cand in ENV_CANDIDATES:
        p = base_dir / cand
        if p.exists() and p.is_file():
            src = p
            break

    if src is None:
        # 没有 .env 可生成：如果已有 .env.example 就算提醒；否则什么也不做
        return

    lines = src.read_text(encoding="utf-8", errors="ignore").splitlines()
    out_lines = []
    out_lines.append("# Auto-generated by make_minimal_zip.py")
    out_lines.append(f"# Source: {src.name}")
    out_lines.append("")

    for ln in lines:
        out_lines.append(sanitize_env_line(ln))

    target.write_text("\n".join(out_lines).rstrip() + "\n", encoding="utf-8")

def should_exclude(rel_path: str) -> bool:
    parts = Path(rel_path).parts

    # 目录层面排除
    for part in parts[:-1]:
        if part in EXCLUDE_DIRS:
            return True
        if match_any_glob(part.lower(), [p.lower() for p in EXCLUDE_DIRNAME_GLOBS]):
            return True

    filename = os.path.basename(rel_path)

    # ✅ 例外：允许把 .env.example 打进 zip（方便团队/AI 复现变量结构）
    # 注意：因为 EXCLUDE_FILE_GLOBS 里有 ".env.*"，所以必须在它之前放行
    if filename == ".env.example":
        return False

    # 文件模式排除
    if match_any_glob(filename, EXCLUDE_FILE_GLOBS) or match_any_glob(rel_path, EXCLUDE_FILE_GLOBS):
        return True

    # SOURCE_ONLY：只收白名单后缀（但允许强制文件名）
    if SOURCE_ONLY:
        if filename in FORCE_INCLUDE_FILENAMES:
            return False
        ext = Path(filename).suffix.lower()
        if ext in ALLOW_EXTS:
            return False
        return True  # 非白名单一律排除

    return False

def add_file(zipf: zipfile.ZipFile, file_path: Path, base_dir: Path):
    rel = str(file_path.relative_to(base_dir)).replace("\\", "/")
    zipf.write(str(file_path), rel)
    return rel

def zip_project(base_dir: str):
    base_dir = Path(base_dir).resolve()

    # ✅ 在打包前生成 .env.example（如果能找到 .env）
    ensure_env_example(base_dir)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    zip_name = f"customor-qc-app_{timestamp}.zip" if SOURCE_ONLY else f"sean-brain-monorepo_full_{timestamp}.zip"

    out_dir = get_desktop_dir() if OUTPUT_TO_DESKTOP else base_dir
    output_path = (out_dir / zip_name).resolve()

    print(f"项目根目录: {base_dir}")
    print(f"输出文件  : {output_path}")
    print(f"模式      : {'SOURCE_ONLY(源码/配置白名单)' if SOURCE_ONLY else 'FULL(除排除项)'}")
    print("-" * 60)

    max_bytes = MAX_FILE_SIZE_MB * 1024 * 1024

    added = 0
    skipped = 0
    skipped_big = 0
    largest = []  # (size, rel)

    with zipfile.ZipFile(str(output_path), "w", zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(str(base_dir)):
            root_path = Path(root)

            # 过滤目录（阻止向下 walk）
            pruned = []
            for d in dirs:
                if d in EXCLUDE_DIRS:
                    continue
                if match_any_glob(d.lower(), [p.lower() for p in EXCLUDE_DIRNAME_GLOBS]):
                    continue
                pruned.append(d)
            dirs[:] = pruned

            for fname in files:
                full_path = root_path / fname
                if not full_path.is_file():
                    continue

                rel = str(full_path.relative_to(base_dir)).replace("\\", "/")

                if should_exclude(rel):
                    skipped += 1
                    continue

                try:
                    size = full_path.stat().st_size
                except OSError:
                    skipped += 1
                    continue

                if size > max_bytes:
                    skipped_big += 1
                    continue

                add_file(zipf, full_path, base_dir)
                added += 1
                largest.append((size, rel))

    largest.sort(reverse=True)
    print("\n✅ 打包完成！")
    print(f"已加入文件数: {added}")
    print(f"跳过(排除规则): {skipped}")
    print(f"跳过(超大文件): {skipped_big}")
    print(f"生成文件: {output_path}")

    print(f"\n📌 最大的 {min(TOP_LARGEST_PRINT, len(largest))} 个文件（方便你定位为什么会大）:")
    for size, rel in largest[:TOP_LARGEST_PRINT]:
        print(f"  {size/1024/1024:.2f} MB  {rel}")

if __name__ == "__main__":
    zip_project(".")
